# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonasty limit
	firstTerm = 1
	secTerm = 2
	array = [2]
	while array.last <= limit
		array.push firstTerm + secTerm
		firstTerm = secTerm
		secTerm = array.last
	end
	array.pop
	array
end

class Array
	
	def makeEven
		evenArray = []
		self.each do |num|
			if num/2 == num.to_f/2.00
				evenArray.push num
			end
		end
	evenArray
	end

	def sumArray
		sum = 0
		self.each do |num|
			sum = sum + num
		end
	sum
	end
end

fibo = fibonasty 50
fibo = fibo.makeEven
puts fibo.sumArray