array = ["1. Given the choice of anyone in the world, whom would you want as a dinner guest?", 
	"Would you like to be famous? In what way?",
	"Before making a telephone call, do you ever rehearse what you are going to say? Why?",
	"What would constitute a “perfect” day for you?",
	"When did you last sing to yourself? To someone else?",
	"Name three things you and your partner appear to have in common.",
	"For what in your life do you feel most grateful?",
	"If you could change anything about the way you were raised, what would it be?",
	"If you could wake up tomorrow having gained any one quality or ability, what would it be?",
	"Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?",
	"What is the greatest accomplishment of your life?",
	"What is your most treasured memory?",
	"What is your most terrible memory?",
	"How close and warm is your family? Do you feel your childhood was happier than most other people’s?",
	"Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?"]
puts array.shuffle[0]